Repository tj-uav/GroundStation, pull requests merged in 2022-11, with the labels that each got.

#112 Document server
  .github/workflows/black.yml
  TCP_client_image.py
  TCP_server_image.py
  client/public/slippy_map_getter.py
  server/.pre-commit-config.yaml
  server/app.py
  server/apps/__init__.py
  server/apps/interop.py
  server/apps/uav.py
  server/apps/ugv.py
  server/groundstation.py
  server/handlers/image.py
  server/handlers/interop/dummy.py
  server/handlers/interop/prod.py
  server/handlers/uav/prod.py
  server/mypy.ini
  server/requirements.txt
  server/utils/clean_directory.py
  server/utils/decorators.py
  server/utils/export_telem.py
  server/utils/logging_setup.py
Labels: documentation, backend

#111 fixed up the logs page; no longer cuts off the scrolling and now refr…
  client/src/pages/FlightData/tabs/Logs.js
  server/app.py
Labels: bug, frontend

#115 Fix Telemetry logging and parsing
  server/utils/export_telem.py
  server/utils/parse_telem.py
Labels: backend
