Repository tj-uav/GroundStation, pull requests merged in 2022-01, with the labels that each got.

#54 Backend Refactor
  .gitignore
  client/package-lock.json
  client/src/components/FlightMap.js
  client/src/components/Header.js
  client/src/pages/FlightData/index.js
  client/src/pages/FlightData/tabs/Quick.js
  server/.pylintrc
  server/app.py
  server/assets/map_images/sample.jpg
  server/assets/map_images/sample.png
  server/assets/odlc_images/0.jpg
  server/assets/odlc_images/1.jpg
  server/assets/odlc_images/2.jpg
  server/assets/odlc_images/3.jpg
  server/assets/odlc_images/sample.jpg
  server/assets/odlc_images/sample.png
  server/clean_directory.py
  server/dummy_mav_handler.py
  server/errors.py
  server/groundstation.py
  server/handlers/dummy_uav_handler.py
  server/handlers/image_handler.py
  server/handlers/interop_handler.py
  server/handlers/uav_handler.py
  server/interop_handler.py
  server/main.py
  server/mav_handler.py
  server/params.py
  server/requirements.txt
  server/sample.config.json
  server/test.py
Labels: backend, refactor

#59 Logging
  .gitignore
  server/app.py
  server/groundstation.py
  server/handlers/dummy_uav_handler.py
  server/handlers/image_handler.py
  server/handlers/interop_handler.py
  server/handlers/uav_handler.py
Labels: feature, backend

#62 ODLC Submission Page
  .gitignore
  client/src/backend.js
  client/src/components/FlightMap.js
  client/src/components/UIElements/Box.js
  client/src/components/UIElements/Checkbox.js
  client/src/components/UIElements/Dropdown.js
  client/src/components/UIElements/Slider.js
  client/src/icons/download.svg
  client/src/icons/save.svg
  client/src/icons/upload.svg
  client/src/pages/FlightData/index.js
  client/src/pages/Submissions/SubmissionEditor.js
  client/src/pages/Submissions/SubmissionsToolbar.js
  client/src/pages/Submissions/Tabs.js
  client/src/pages/Submissions/constants.js
  client/src/pages/Submissions/index.js
  client/src/pages/Submissions/tabs/Submitted.js
  client/src/pages/Submissions/tabs/View.js
  client/src/pages/Submissions/toolbarForm.js
  client/src/theme/Colors.js
  server/app.py
  server/assets/odlc_images/4.jpg
  server/groundstation.py
  server/handlers/dummy_uav_handler.py
  server/handlers/image_handler.py
  server/handlers/interop_handler.py
  server/handlers/uav_handler.py
Labels: feature, frontend

#61 Image handler
  client/src/components/Header.js
  server/app.py
  server/assets/odlc_images/4.jpg
  server/groundstation.py
  server/handlers/dummy_uav_handler.py
  server/handlers/image_handler.py
  server/handlers/interop_handler.py
  server/handlers/uav_handler.py
  server/requirements.txt
  server/sample.config.json
Labels: feature, backend
